name: dart_frog_playground
description: An new Dart Frog application
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  crypto: ^3.0.2
  dart_frog: ^0.1.0
  dotenv: ^4.0.1
  jaguar_jwt: ^3.0.0
  uuid: ^3.0.6

dev_dependencies:
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^3.0.1

assets:
  - views/